name: Release metadata

on:
  workflow_dispatch:

env:
  flutter-version: '3.44.1'

jobs:
  release-metadata:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Flutter version is ${{ env.flutter-version }}"
